import {
  samfrodocampsites,
  gandalfthewhitecampsites,
} from './campsite_data.js';

const buildSamFrodoImage = (fileName) => new URL(`./assets/stories/sam_frodo/${fileName}`, import.meta.url).href;
const buildGandalfTheWhiteImage = (fileName) => new URL(`./assets/stories/gandalf_the_white/${fileName}`, import.meta.url).href;

const samFrodoScenes = [
  {
    markerKey: 'September23',
    title: 'Leaving the Shire',
    date: 'September 23',
    location: 'Green Hill Country',
    narrative: 'Frodo, Sam, and Pippin begin their first deliberate march away from the comforts of the Shire. The road still feels familiar, but the mood has shifted: every hedgerow now seems to carry the shadow of pursuit.',
    camp: 'Green Hill Country',
    hoursOnRoad: '5',
    milesTraveled: '18',
    pace: '3.6 mph',
    roadNotes: 'Evening march.',
    imageFileName: 'scene-01.png',
  },
  {
    markerKey: 'September24',
    title: 'Black Riders on the Road',
    date: 'September 24',
    location: 'West of Woodhall',
    narrative: 'The company presses on and the menace grows sharper. Black Riders haunt the road while an Elvish encounter briefly reminds the hobbits that the wider world still holds beauty, music, and allies.',
    camp: 'West of Woodhall',
    hoursOnRoad: '8',
    milesTraveled: '28',
    pace: '3.5 mph',
    roadNotes: 'Black Riders, Elves.',
    imageFileName: 'scene-02.png',
  },
  {
    markerKey: 'September25',
    title: 'Farmer Maggot and the Ferry East',
    date: 'September 25',
    location: 'Crickhollow',
    narrative: `The hobbits cross the Brandywine River and the Marish and encounter a friendly, yet shrewd hobbit by the name of Farmer Maggot. A friend of Tom Bombadil's, Maggot had much knowledge on the goings-on of the Shire. He also gave the three hobbits supplies for their journey.`,
    camp: 'Crickhollow',
    hoursOnRoad: '7.5',
    milesTraveled: '27',
    pace: '10.4 mph',
    roadNotes: 'Marish, Farmer Maggot wagon, Buckland.',
    imageFileName: 'scene-03.png',
  },
  {
    markerKey: 'September26',
    title: 'Into the Old Forest',
    date: 'September 26',
    location: 'The House of Tom Bombadil',
    narrative: 'Ponies carry them into the strange green silence beyond Buckland. The Forest seems to watch them, Old Man Willow nearly claims them, and Tom Bombadil’s house becomes a sudden pocket of song and safety.',
    camp: 'The House of Tom Bombadil',
    hoursOnRoad: '10.5',
    milesTraveled: '25',
    pace: '2.4 mph',
    roadNotes: 'On ponies. Knoll, Old Man Willow.',
    imageFileName: 'scene-04.png',
  },
  {
    markerKey: 'September27',
    title: 'A Rainy Respite with Tom',
    date: 'September 27',
    location: 'The House of Tom Bombadil',
    narrative: 'Rain keeps the company at Bombadil’s house for another day. It is a pause in the narrative, but an important one: the hobbits are allowed to breathe, listen, and gather a little courage before the Old Forest gives way to older terrors.',
    camp: 'The House of Tom Bombadil',
    hoursOnRoad: 'Unknown',
    milesTraveled: 'Unknown',
    pace: 'Unknown',
    roadNotes: 'Rain.',
    imageFileName: 'scene-05.png',
  },
  {
    markerKey: 'September28',
    title: 'Taken by the Barrow',
    date: 'September 28',
    location: 'Barrow',
    narrative: 'The road east becomes truly haunted. After a weary day and afternoon sleep, the company is captured in the Barrow-downs, and their Shire adventure begins to resemble an ancient tale of graves, cold stones, and forgotten kings.',
    camp: 'Barrow',
    hoursOnRoad: '5',
    milesTraveled: '17',
    pace: '3.4 mph',
    roadNotes: 'Ponies. Sleep afternoon, captured in evening.',
    imageFileName: 'scene-06.png',
  },
  {
    markerKey: 'September29',
    title: 'Bree at Last - Encounter with Strider',
    date: 'September 29',
    location: 'Bree',
    narrative: 'Freed from the Barrow and riding once more, Frodo and his companions finally reach Bree. The Prancing Pony offers shelter and news, but this crossing point between Hobbit-land and the wider world also brings new risks and fateful meetings.',
    camp: 'Bree',
    hoursOnRoad: '6',
    milesTraveled: '20',
    pace: '3.3 mph',
    roadNotes: 'Ponies. Start after lunch.',
    imageFileName: 'scene-07.png',
  },
  {
    markerKey: 'September30',
    title: 'Heading Out with Strider',
    date: 'September 30',
    location: 'Western Chetwood',
    narrative: 'After an attack by the Ring Wraiths, the hobbits and Strider head out for Rivendell. The first stop is Western Chetwood.',
    camp: 'Bree',
    hoursOnRoad: '6',
    milesTraveled: '20',
    pace: '3.3 mph',
    roadNotes: 'Ponies. Start after lunch.',
    imageFileName: 'scene-08.png',
  },

].map((scene, index) => ({
  ...scene,
  coords: samfrodocampsites[scene.markerKey].coords,
  image: buildSamFrodoImage(scene.imageFileName),
  imageRelativePath: `maps/middle_earth/assets/stories/sam_frodo/${scene.imageFileName}`,
  zoom: 19,
  order: index + 1,
}));

const gandalfTheWhiteScenes = [
  {
    markerKey: 'February14',
    title: 'Awakening on Zirakzigil',
    date: 'February 14',
    location: 'Peak of the Silvertine (Celebdil)',
    narrative: `After his struggle with the Balrog is ended, Gandalf returns to life high upon Zirakzigil. Alone on the wind-scoured peak, he lies in a trance while Middle-earth moves on below him, and the Grey Pilgrim begins to pass into a new and greater charge.`,
    camp: 'Peak of the Silvertine (Celebdil) Mountain',
    hoursOnRoad: 'Unknown',
    milesTraveled: 'Unknown',
    pace: 'Unknown',
    roadNotes: 'Gandalf returns to life and lies upon the peak in a trance.',
    imageFileName: 'scene-01.png',
  },
  {
    markerKey: 'February17',
    title: 'Gwaihir Bears Him to Lothlorien',
    date: 'February 17',
    location: 'Lothlorien',
    narrative: `Three days later, Gwaihir the Windlord finds Gandalf on the heights and carries him away from the mountains. The journey is swift and strange: from the white crown of Celebdil to the golden refuge of Lothlorien, where rest, counsel, and renewal await the newly returned wizard.`,
    camp: 'Lothlorien',
    hoursOnRoad: 'Unknown',
    milesTraveled: 'Unknown',
    pace: 'Unknown',
    roadNotes: 'Gwaihir carries Gandalf south from the mountains into Lothlorien.',
    imageFileName: 'scene-02.png',
  },
  {
    markerKey: 'February18',
    title: 'Galdriel Clothes Him in White',
    date: 'February 18',
    location: 'Lothlorien',
    narrative: `Gandalf arrives in Lothlorien for much needed rest and respite. He meets his old friend Galadriel, and recognizing the sacrifice he made defending the Fellowship against the terrible terror awoken from the depths of Moria, she graciously clothes him in his white garb. Steadfast and earnest in his dedication to his mission of helping the free peoples of Middle-earth defeat Sauron, he is now Gandalf the White.`,
    camp: 'Lothlorien',
    hoursOnRoad: 'Unknown',
    milesTraveled: 'Unknown',
    pace: 'Unknown',
    roadNotes: 'Galadriel meets Gandalf in Lothlorien and clothes him in his well-earned white robe.',
    imageFileName: 'scene-03.png',
  },
].map((scene, index) => ({
  ...scene,
  coords: gandalfthewhitecampsites[scene.markerKey].coords,
  image: buildGandalfTheWhiteImage(scene.imageFileName),
  imageRelativePath: `maps/middle_earth/assets/stories/gandalf_the_white/${scene.imageFileName}`,
  zoom: 19,
  order: index + 1,
}));

export const curatedStories = [
  {
    id: 'sam-frodo-first-seven',
    title: 'Sam and Frodo: From the Shire to Bree',
    markerGroupName: 'samfrodocampsites',
    campCheckboxId: 'samfrodocampsitesCheckbox',
    pathCheckboxId: 'samfrodopathCheckbox',
    scenes: samFrodoScenes,
  },
  {
    id: 'gandalf-the-white-first-two',
    title: 'Gandalf the White: From Zirakzigil to Lothlorien',
    markerGroupName: 'gandalfthewhitecampsites',
    campCheckboxId: 'gandalfthewhitecampsitesCheckbox',
    pathCheckboxId: 'gandalfthewhitepathCheckbox',
    scenes: gandalfTheWhiteScenes,
  },
];

export const getCuratedStoryById = (storyId) => {
  return curatedStories.find((story) => story.id === storyId) || null;
};
